name: Deploy Quartz site to GitHub Pages
 
on:
  push:
    branches:
      - v4
 
permissions:
  contents: read
  pages: write
  id-token: write
 
concurrency:
  group: "pages"
  cancel-in-progress: false
 
jobs:
  build-and-upload:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git info
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Dependencies
        run: npm ci
      - name: Build Quartz
        run: npx quartz build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      - name: Initialize the ssh-agent # configure ssh private key
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.ORACLE_ARM_X_KEY }}

  # SSH keyscan to avoid error
      - name: Scan the host key
        run: mkdir -p ~/.ssh/ && ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts
        env:
          DEPLOY_SERVER: ${{ secrets.ORACLE_ARM_X_IP }}

  # Runs the rsync command to the remote site (caddy reverse proxy)
      - name: Deploy the website
        run: >-
            rsync -avx --delete --exclude '.ssh' --exclude '.git' public/ $DEPLOY_USERNAME@$DEPLOY_SERVER:./docker/caddy/www
        env:
          DEPLOY_SERVER: ${{ secrets.ORACLE_ARM_X_IP }}
          DEPLOY_USERNAME: ubuntu

  deploy:
    needs: build-and-upload
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4